apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
  labels:
    app: register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
        - name: register
          image: bishnupoudel/register:v2
          envFrom:
            - configMapRef:
                name: register-configmap
            - secretRef:
                name: register-secret
